### ISSUE TITLE
reader funksjonalitet

### ISSUE THREAD

**Issue by tonystr** [githansen/bachelor_frontend#14]

**Comment by junus-sefa** [comment]
Har lagt inn mulighet for bruker å endre tekststørrelse, fontfamily og bakgrunnsfarge. Har lagt til det i "first-implementation" branchen.





![Image](https://user-images.githubusercontent.com/72740756/215298351-920cd0b1-9e7e-421c-b91f-f66c5e80b3e8.png)

**Comment by junus-sefa** [comment]
LAGT TIL:
- Mulighet for å endre dark/light theme
- Tekst størrelse, teksttype, justering av tekst

![Image](https://user-images.githubusercontent.com/72740756/216332336-a3d2e311-cf23-4913-a973-2b09e12c281c.png)

![Image](https://user-images.githubusercontent.com/72740756/216332386-9e4a8c64-d188-4e27-8a06-46c9b9129520.png)
