### ISSUE TITLE
Implementere "Takk for bidrag" side

### ISSUE THREAD

**Issue by tonystr** [githansen/bachelor_frontend#9]
![Image](https://user-images.githubusercontent.com/30723101/213418646-e3cb9567-37b3-474a-bcc7-044ac0b86208.png)

**Comment by junus-sefa** [comment]
![Image](https://user-images.githubusercontent.com/72740756/215297539-038af911-640c-4af7-8036-98b0be27de6e.png)

Implementert nytt design. Ikon hentet fra SALY https://www.figma.com/file/x5pXJXtLBCLOzGgR8dbuNm/SALY---3D-Illustration-Pack-(Community)?node-id=135%3A36&t=GdiF6XJ2XMw0Xoek-0
